### ISSUE TITLE
No query string in POST requests

### ISSUE THREAD

**Issue by rickdzekman** [intolerable/api-builder#3]
I had a whole bunch of code for managing API connections that I've almost completely replaced with this library. This is great work.

But I have an issue with the instance instance `Sendable ()`. Because I can't override an instance in Haskell I've basically had to to re-implement a lot of `Network.API.Builder.API`.

The issue is that it converts all query string parameters into body arguments for a POST request:

      "POST" -> do
        req <- parseUrl $ Text.unpack $ routeURL (_baseURL builder) (_customizeRoute builder r)
        return $ _customizeRequest builder $
          req { requestHeaders = ("Content-Type", "application/x-www-form-urlencoded") : requestHeaders req
              , requestBody = RequestBodyBS (dropQuestion $ queryString req)
              , queryString = ""
              , method = httpMethod r }

Unfortunately one of the APIs I'm working with expects the arguments as a query string. If I need to add body arguments I can always modify the request with `_customizeRequest`. I've simply re-implemented send like so:

    send' :: MonadThrow m => Builder -> Route -> m Request
    send' builder r = do
            req <- parseUrl $ unpack $ routeURL (_baseURL builder) (_customizeRoute builder r)
            return $ _customizeRequest builder $ req { method = httpMethod r }

Not really sure if this is an issue you want to fix. This library really simplified some things for me so I figured I'd let you know.

**Comment by intolerable** [comment]
If I add a `newtype` for "keep the POST params in the query", would that solve your problem?

**Comment by intolerable** [comment]
if you `send` `PostQuery` instead of `()`, it'll keep the query params in the params (rather than shifting them into the body).

**Comment by rickdzekman** [comment]
That worked perfectly. Thanks.
